FROM resin/%%RESIN_MACHINE_NAME%%-python:2

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY tree.py ./

ENV INITSYSTEM on

CMD ["python", "tree.py"]
